;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/brightness-control]
type = custom/script
exec = ~/your_path/brightness.sh watch
interval = 0
tail = true
format = <label>
format-prefix = "%{T1}"
label = %output%
scroll-up = ~/your_path/brightness.sh inc
scroll-down = ~/your_path/brightness.sh dec
cursor-scroll = ns-resize

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/brightness1-control]
type = custom/script
exec = ~/your_path/brightness1.sh watch
interval = 0
tail = true
format = <label>
format-prefix = "%{T1}"
label = %output%
scroll-up = ~/your_path/brightness1.sh inc
scroll-down = ~/your_path/brightness1.sh dec
cursor-scroll = ns-resize

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
